name: school_task_manager
description: A personal school task manager for German education system

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.4.0
  sqflite_common_ffi: ^2.0.0+2
  path_provider: ^2.1.1
  provider: ^6.1.1
  flutter_localizations:
    sdk: flutter
  google_fonts: ^6.1.0
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_svg: ^2.0.9
  phosphor_flutter: ^2.0.1
  fl_chart: ^0.66.0
  flutter_animate: ^4.5.0
  calendar_view: ^1.0.4
  flutter_slidable: ^3.0.1
  cached_network_image: ^3.3.1
  lottie: ^2.7.0
  glassmorphism: ^3.0.0
  intl: ^0.19.0
  uuid: ^4.2.1
  window_manager: ^0.4.3
  bitsdojo_window: ^0.1.6
  flutter_time_picker_spinner: ^2.0.0
  material_symbols_icons: ^4.2719.1
  iconsax: ^0.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  hive_generator: ^2.0.0
  
